create table zawadzki.customer( 
id integer primary key GENERATED BY DEFAULT AS IDENTITY, 
firstName varchar(50), 
lastName varchar(50), 
address varchar(50),
pesel varchar(11) unique, 
email varchar(50) ); 
create table zawadzki.account ( 
id integer primary key GENERATED BY DEFAULT AS IDENTITY, 
notes varchar(255), 
balance double, 
id_customer integer constraint fk_customer references zawadzki.customer on delete cascade);